# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import platform_iface_pb2 as grpc__stubs_dot_platform__iface__pb2


class platformIfaceStub(object):
    """The doover device agent service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TestComms = channel.unary_unary(
                '/platform_iface.platformIface/TestComms',
                request_serializer=grpc__stubs_dot_platform__iface__pb2.TestCommsRequest.SerializeToString,
                response_deserializer=grpc__stubs_dot_platform__iface__pb2.TestCommsResponse.FromString,
                )
        self.getDI = channel.unary_unary(
                '/platform_iface.platformIface/getDI',
                request_serializer=grpc__stubs_dot_platform__iface__pb2.getDIRequest.SerializeToString,
                response_deserializer=grpc__stubs_dot_platform__iface__pb2.getDIResponse.FromString,
                )
        self.getAI = channel.unary_unary(
                '/platform_iface.platformIface/getAI',
                request_serializer=grpc__stubs_dot_platform__iface__pb2.getAIRequest.SerializeToString,
                response_deserializer=grpc__stubs_dot_platform__iface__pb2.getAIResponse.FromString,
                )
        self.startPulseCounter = channel.unary_stream(
                '/platform_iface.platformIface/startPulseCounter',
                request_serializer=grpc__stubs_dot_platform__iface__pb2.pulseCounterRequest.SerializeToString,
                response_deserializer=grpc__stubs_dot_platform__iface__pb2.pulseCounterResponse.FromString,
                )
        self.getDO = channel.unary_unary(
                '/platform_iface.platformIface/getDO',
                request_serializer=grpc__stubs_dot_platform__iface__pb2.getDORequest.SerializeToString,
                response_deserializer=grpc__stubs_dot_platform__iface__pb2.getDOResponse.FromString,
                )
        self.setDO = channel.unary_unary(
                '/platform_iface.platformIface/setDO',
                request_serializer=grpc__stubs_dot_platform__iface__pb2.setDORequest.SerializeToString,
                response_deserializer=grpc__stubs_dot_platform__iface__pb2.setDOResponse.FromString,
                )
        self.scheduleDO = channel.unary_unary(
                '/platform_iface.platformIface/scheduleDO',
                request_serializer=grpc__stubs_dot_platform__iface__pb2.scheduleDORequest.SerializeToString,
                response_deserializer=grpc__stubs_dot_platform__iface__pb2.scheduleDOResponse.FromString,
                )
        self.getAO = channel.unary_unary(
                '/platform_iface.platformIface/getAO',
                request_serializer=grpc__stubs_dot_platform__iface__pb2.getAORequest.SerializeToString,
                response_deserializer=grpc__stubs_dot_platform__iface__pb2.getAOResponse.FromString,
                )
        self.setAO = channel.unary_unary(
                '/platform_iface.platformIface/setAO',
                request_serializer=grpc__stubs_dot_platform__iface__pb2.setAORequest.SerializeToString,
                response_deserializer=grpc__stubs_dot_platform__iface__pb2.setAOResponse.FromString,
                )
        self.scheduleAO = channel.unary_unary(
                '/platform_iface.platformIface/scheduleAO',
                request_serializer=grpc__stubs_dot_platform__iface__pb2.scheduleAORequest.SerializeToString,
                response_deserializer=grpc__stubs_dot_platform__iface__pb2.scheduleAOResponse.FromString,
                )
        self.getValue = channel.unary_unary(
                '/platform_iface.platformIface/getValue',
                request_serializer=grpc__stubs_dot_platform__iface__pb2.getValueRequest.SerializeToString,
                response_deserializer=grpc__stubs_dot_platform__iface__pb2.getValueResponse.FromString,
                )
        self.setValue = channel.unary_unary(
                '/platform_iface.platformIface/setValue',
                request_serializer=grpc__stubs_dot_platform__iface__pb2.setValueRequest.SerializeToString,
                response_deserializer=grpc__stubs_dot_platform__iface__pb2.setValueResponse.FromString,
                )
        self.getSystemStatus = channel.unary_unary(
                '/platform_iface.platformIface/getSystemStatus',
                request_serializer=grpc__stubs_dot_platform__iface__pb2.getSystemStatusRequest.SerializeToString,
                response_deserializer=grpc__stubs_dot_platform__iface__pb2.getSystemStatusResponse.FromString,
                )
        self.scheduleStartup = channel.unary_unary(
                '/platform_iface.platformIface/scheduleStartup',
                request_serializer=grpc__stubs_dot_platform__iface__pb2.scheduleStartupRequest.SerializeToString,
                response_deserializer=grpc__stubs_dot_platform__iface__pb2.scheduleStartupResponse.FromString,
                )
        self.scheduleShutdown = channel.unary_unary(
                '/platform_iface.platformIface/scheduleShutdown',
                request_serializer=grpc__stubs_dot_platform__iface__pb2.scheduleShutdownRequest.SerializeToString,
                response_deserializer=grpc__stubs_dot_platform__iface__pb2.scheduleShutdownResponse.FromString,
                )
        self.reboot = channel.unary_unary(
                '/platform_iface.platformIface/reboot',
                request_serializer=grpc__stubs_dot_platform__iface__pb2.rebootRequest.SerializeToString,
                response_deserializer=grpc__stubs_dot_platform__iface__pb2.rebootResponse.FromString,
                )
        self.shutdown = channel.unary_unary(
                '/platform_iface.platformIface/shutdown',
                request_serializer=grpc__stubs_dot_platform__iface__pb2.shutdownRequest.SerializeToString,
                response_deserializer=grpc__stubs_dot_platform__iface__pb2.shutdownResponse.FromString,
                )


class platformIfaceServicer(object):
    """The doover device agent service definition.
    """

    def TestComms(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getDI(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getAI(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def startPulseCounter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getDO(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def setDO(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def scheduleDO(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getAO(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def setAO(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def scheduleAO(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def setValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getSystemStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def scheduleStartup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def scheduleShutdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def reboot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def shutdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_platformIfaceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TestComms': grpc.unary_unary_rpc_method_handler(
                    servicer.TestComms,
                    request_deserializer=grpc__stubs_dot_platform__iface__pb2.TestCommsRequest.FromString,
                    response_serializer=grpc__stubs_dot_platform__iface__pb2.TestCommsResponse.SerializeToString,
            ),
            'getDI': grpc.unary_unary_rpc_method_handler(
                    servicer.getDI,
                    request_deserializer=grpc__stubs_dot_platform__iface__pb2.getDIRequest.FromString,
                    response_serializer=grpc__stubs_dot_platform__iface__pb2.getDIResponse.SerializeToString,
            ),
            'getAI': grpc.unary_unary_rpc_method_handler(
                    servicer.getAI,
                    request_deserializer=grpc__stubs_dot_platform__iface__pb2.getAIRequest.FromString,
                    response_serializer=grpc__stubs_dot_platform__iface__pb2.getAIResponse.SerializeToString,
            ),
            'startPulseCounter': grpc.unary_stream_rpc_method_handler(
                    servicer.startPulseCounter,
                    request_deserializer=grpc__stubs_dot_platform__iface__pb2.pulseCounterRequest.FromString,
                    response_serializer=grpc__stubs_dot_platform__iface__pb2.pulseCounterResponse.SerializeToString,
            ),
            'getDO': grpc.unary_unary_rpc_method_handler(
                    servicer.getDO,
                    request_deserializer=grpc__stubs_dot_platform__iface__pb2.getDORequest.FromString,
                    response_serializer=grpc__stubs_dot_platform__iface__pb2.getDOResponse.SerializeToString,
            ),
            'setDO': grpc.unary_unary_rpc_method_handler(
                    servicer.setDO,
                    request_deserializer=grpc__stubs_dot_platform__iface__pb2.setDORequest.FromString,
                    response_serializer=grpc__stubs_dot_platform__iface__pb2.setDOResponse.SerializeToString,
            ),
            'scheduleDO': grpc.unary_unary_rpc_method_handler(
                    servicer.scheduleDO,
                    request_deserializer=grpc__stubs_dot_platform__iface__pb2.scheduleDORequest.FromString,
                    response_serializer=grpc__stubs_dot_platform__iface__pb2.scheduleDOResponse.SerializeToString,
            ),
            'getAO': grpc.unary_unary_rpc_method_handler(
                    servicer.getAO,
                    request_deserializer=grpc__stubs_dot_platform__iface__pb2.getAORequest.FromString,
                    response_serializer=grpc__stubs_dot_platform__iface__pb2.getAOResponse.SerializeToString,
            ),
            'setAO': grpc.unary_unary_rpc_method_handler(
                    servicer.setAO,
                    request_deserializer=grpc__stubs_dot_platform__iface__pb2.setAORequest.FromString,
                    response_serializer=grpc__stubs_dot_platform__iface__pb2.setAOResponse.SerializeToString,
            ),
            'scheduleAO': grpc.unary_unary_rpc_method_handler(
                    servicer.scheduleAO,
                    request_deserializer=grpc__stubs_dot_platform__iface__pb2.scheduleAORequest.FromString,
                    response_serializer=grpc__stubs_dot_platform__iface__pb2.scheduleAOResponse.SerializeToString,
            ),
            'getValue': grpc.unary_unary_rpc_method_handler(
                    servicer.getValue,
                    request_deserializer=grpc__stubs_dot_platform__iface__pb2.getValueRequest.FromString,
                    response_serializer=grpc__stubs_dot_platform__iface__pb2.getValueResponse.SerializeToString,
            ),
            'setValue': grpc.unary_unary_rpc_method_handler(
                    servicer.setValue,
                    request_deserializer=grpc__stubs_dot_platform__iface__pb2.setValueRequest.FromString,
                    response_serializer=grpc__stubs_dot_platform__iface__pb2.setValueResponse.SerializeToString,
            ),
            'getSystemStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.getSystemStatus,
                    request_deserializer=grpc__stubs_dot_platform__iface__pb2.getSystemStatusRequest.FromString,
                    response_serializer=grpc__stubs_dot_platform__iface__pb2.getSystemStatusResponse.SerializeToString,
            ),
            'scheduleStartup': grpc.unary_unary_rpc_method_handler(
                    servicer.scheduleStartup,
                    request_deserializer=grpc__stubs_dot_platform__iface__pb2.scheduleStartupRequest.FromString,
                    response_serializer=grpc__stubs_dot_platform__iface__pb2.scheduleStartupResponse.SerializeToString,
            ),
            'scheduleShutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.scheduleShutdown,
                    request_deserializer=grpc__stubs_dot_platform__iface__pb2.scheduleShutdownRequest.FromString,
                    response_serializer=grpc__stubs_dot_platform__iface__pb2.scheduleShutdownResponse.SerializeToString,
            ),
            'reboot': grpc.unary_unary_rpc_method_handler(
                    servicer.reboot,
                    request_deserializer=grpc__stubs_dot_platform__iface__pb2.rebootRequest.FromString,
                    response_serializer=grpc__stubs_dot_platform__iface__pb2.rebootResponse.SerializeToString,
            ),
            'shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.shutdown,
                    request_deserializer=grpc__stubs_dot_platform__iface__pb2.shutdownRequest.FromString,
                    response_serializer=grpc__stubs_dot_platform__iface__pb2.shutdownResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'platform_iface.platformIface', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class platformIface(object):
    """The doover device agent service definition.
    """

    @staticmethod
    def TestComms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/platform_iface.platformIface/TestComms',
            grpc__stubs_dot_platform__iface__pb2.TestCommsRequest.SerializeToString,
            grpc__stubs_dot_platform__iface__pb2.TestCommsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getDI(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/platform_iface.platformIface/getDI',
            grpc__stubs_dot_platform__iface__pb2.getDIRequest.SerializeToString,
            grpc__stubs_dot_platform__iface__pb2.getDIResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getAI(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/platform_iface.platformIface/getAI',
            grpc__stubs_dot_platform__iface__pb2.getAIRequest.SerializeToString,
            grpc__stubs_dot_platform__iface__pb2.getAIResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def startPulseCounter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/platform_iface.platformIface/startPulseCounter',
            grpc__stubs_dot_platform__iface__pb2.pulseCounterRequest.SerializeToString,
            grpc__stubs_dot_platform__iface__pb2.pulseCounterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getDO(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/platform_iface.platformIface/getDO',
            grpc__stubs_dot_platform__iface__pb2.getDORequest.SerializeToString,
            grpc__stubs_dot_platform__iface__pb2.getDOResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def setDO(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/platform_iface.platformIface/setDO',
            grpc__stubs_dot_platform__iface__pb2.setDORequest.SerializeToString,
            grpc__stubs_dot_platform__iface__pb2.setDOResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def scheduleDO(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/platform_iface.platformIface/scheduleDO',
            grpc__stubs_dot_platform__iface__pb2.scheduleDORequest.SerializeToString,
            grpc__stubs_dot_platform__iface__pb2.scheduleDOResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getAO(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/platform_iface.platformIface/getAO',
            grpc__stubs_dot_platform__iface__pb2.getAORequest.SerializeToString,
            grpc__stubs_dot_platform__iface__pb2.getAOResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def setAO(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/platform_iface.platformIface/setAO',
            grpc__stubs_dot_platform__iface__pb2.setAORequest.SerializeToString,
            grpc__stubs_dot_platform__iface__pb2.setAOResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def scheduleAO(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/platform_iface.platformIface/scheduleAO',
            grpc__stubs_dot_platform__iface__pb2.scheduleAORequest.SerializeToString,
            grpc__stubs_dot_platform__iface__pb2.scheduleAOResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/platform_iface.platformIface/getValue',
            grpc__stubs_dot_platform__iface__pb2.getValueRequest.SerializeToString,
            grpc__stubs_dot_platform__iface__pb2.getValueResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def setValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/platform_iface.platformIface/setValue',
            grpc__stubs_dot_platform__iface__pb2.setValueRequest.SerializeToString,
            grpc__stubs_dot_platform__iface__pb2.setValueResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getSystemStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/platform_iface.platformIface/getSystemStatus',
            grpc__stubs_dot_platform__iface__pb2.getSystemStatusRequest.SerializeToString,
            grpc__stubs_dot_platform__iface__pb2.getSystemStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def scheduleStartup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/platform_iface.platformIface/scheduleStartup',
            grpc__stubs_dot_platform__iface__pb2.scheduleStartupRequest.SerializeToString,
            grpc__stubs_dot_platform__iface__pb2.scheduleStartupResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def scheduleShutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/platform_iface.platformIface/scheduleShutdown',
            grpc__stubs_dot_platform__iface__pb2.scheduleShutdownRequest.SerializeToString,
            grpc__stubs_dot_platform__iface__pb2.scheduleShutdownResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def reboot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/platform_iface.platformIface/reboot',
            grpc__stubs_dot_platform__iface__pb2.rebootRequest.SerializeToString,
            grpc__stubs_dot_platform__iface__pb2.rebootResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/platform_iface.platformIface/shutdown',
            grpc__stubs_dot_platform__iface__pb2.shutdownRequest.SerializeToString,
            grpc__stubs_dot_platform__iface__pb2.shutdownResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
