# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import camera_iface_pb2 as grpc__stubs_dot_camera__iface__pb2


class cameraIfaceStub(object):
    """The doover device agent service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TestComms = channel.unary_unary(
                '/camera_iface.cameraIface/TestComms',
                request_serializer=grpc__stubs_dot_camera__iface__pb2.TestCommsRequest.SerializeToString,
                response_deserializer=grpc__stubs_dot_camera__iface__pb2.TestCommsResponse.FromString,
                )
        self.RunSnapshot = channel.unary_unary(
                '/camera_iface.cameraIface/RunSnapshot',
                request_serializer=grpc__stubs_dot_camera__iface__pb2.SnapshotRequest.SerializeToString,
                response_deserializer=grpc__stubs_dot_camera__iface__pb2.SnapshotResponse.FromString,
                )


class cameraIfaceServicer(object):
    """The doover device agent service definition.
    """

    def TestComms(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_cameraIfaceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TestComms': grpc.unary_unary_rpc_method_handler(
                    servicer.TestComms,
                    request_deserializer=grpc__stubs_dot_camera__iface__pb2.TestCommsRequest.FromString,
                    response_serializer=grpc__stubs_dot_camera__iface__pb2.TestCommsResponse.SerializeToString,
            ),
            'RunSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.RunSnapshot,
                    request_deserializer=grpc__stubs_dot_camera__iface__pb2.SnapshotRequest.FromString,
                    response_serializer=grpc__stubs_dot_camera__iface__pb2.SnapshotResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'camera_iface.cameraIface', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class cameraIface(object):
    """The doover device agent service definition.
    """

    @staticmethod
    def TestComms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/camera_iface.cameraIface/TestComms',
            grpc__stubs_dot_camera__iface__pb2.TestCommsRequest.SerializeToString,
            grpc__stubs_dot_camera__iface__pb2.TestCommsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RunSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/camera_iface.cameraIface/RunSnapshot',
            grpc__stubs_dot_camera__iface__pb2.SnapshotRequest.SerializeToString,
            grpc__stubs_dot_camera__iface__pb2.SnapshotResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
